### ISSUE TITLE
problem compiling ncurses

### ISSUE THREAD

**Issue by pietrondo** [c9/install#24]
I'm trying to install but after 
```

./scripts/install-sdk.sh script
```

During ncurses compiling appear this error:
```

ar -curv ../lib/libform_g.a ../obj_g/f_trace.o ../obj_g/fld_arg.o ../obj_g/fld_attr.o ../obj_g/fld_current.o ../obj_g/fld_def.o ../obj_g/fld_dup.o ../obj_g/fld_ftchoice.o ../obj_g/fld_ftlink.o ../obj_g/fld_info.o ../obj_g/fld_just.o ../obj_g/fld_link.o ../obj_g/fld_max.o ../obj_g/fld_move.o ../obj_g/fld_newftyp.o ../obj_g/fld_opts.o ../obj_g/fld_pad.o ../obj_g/fld_page.o ../obj_g/fld_stat.o ../obj_g/fld_type.o ../obj_g/fld_user.o ../obj_g/frm_cursor.o ../obj_g/frm_data.o ../obj_g/frm_def.o ../obj_g/frm_driver.o ../obj_g/frm_hook.o ../obj_g/frm_opts.o ../obj_g/frm_page.o ../obj_g/frm_post.o ../obj_g/frm_req_name.o ../obj_g/frm_scale.o ../obj_g/frm_sub.o ../obj_g/frm_user.o ../obj_g/frm_win.o ../obj_g/fty_alnum.o ../obj_g/fty_alpha.o ../obj_g/fty_enum.o ../obj_g/fty_generic.o ../obj_g/fty_int.o ../obj_g/fty_ipv4.o ../obj_g/fty_num.o ../obj_g/fty_regex.o
r - ../obj_g/f_trace.o
r - ../obj_g/fld_arg.o
r - ../obj_g/fld_attr.o
r - ../obj_g/fld_current.o
r - ../obj_g/fld_def.o
r - ../obj_g/fld_dup.o
r - ../obj_g/fld_ftchoice.o
r - ../obj_g/fld_ftlink.o
r - ../obj_g/fld_info.o
r - ../obj_g/fld_just.o
r - ../obj_g/fld_link.o
r - ../obj_g/fld_max.o
r - ../obj_g/fld_move.o
r - ../obj_g/fld_newftyp.o
r - ../obj_g/fld_opts.o
r - ../obj_g/fld_pad.o
r - ../obj_g/fld_page.o
r - ../obj_g/fld_stat.o
r - ../obj_g/fld_type.o
r - ../obj_g/fld_user.o
r - ../obj_g/frm_cursor.o
r - ../obj_g/frm_data.o
r - ../obj_g/frm_def.o
r - ../obj_g/frm_driver.o
r - ../obj_g/frm_hook.o
r - ../obj_g/frm_opts.o
r - ../obj_g/frm_page.o
r - ../obj_g/frm_post.o
r - ../obj_g/frm_req_name.o
r - ../obj_g/frm_scale.o
r - ../obj_g/frm_sub.o
r - ../obj_g/frm_user.o
r - ../obj_g/frm_win.o
r - ../obj_g/fty_alnum.o
r - ../obj_g/fty_alpha.o
r - ../obj_g/fty_enum.o
r - ../obj_g/fty_generic.o
r - ../obj_g/fty_int.o
r - ../obj_g/fty_ipv4.o
r - ../obj_g/fty_num.o
r - ../obj_g/fty_regex.o
ranlib ../lib/libform_g.a
make[1]: uscita dalla directory "/home/pietro/.c9/ncurses-5.9/form"
cd test && make DESTDIR="" all
make[1]: ingresso nella directory "/home/pietro/.c9/ncurses-5.9/test"
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param max-inline-insns-single=1200  -c ../test/background.c -o ../objects/background.o
gcc -O2 --param max-inline-insns-single=1200  -o background ../objects/background.o  -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param max-inline-insns-single=1200  `echo "-static -L../lib -lform -lmenu -lpanel -lncurses  -dynamic  -ldl " | sed -e 's/-lform.*-lpanel[^ ]*//'` -lutil  -lm
/usr/bin/ld: impossibile trovare -lutil
collect2: error: ld returned 1 exit status
Makefile:229: set di istruzioni per l'obiettivo "background" non riuscito
make[1]: *** [background] Errore 1
make[1]: uscita dalla directory "/home/pietro/.c9/ncurses-5.9/test"
Makefile:109: set di istruzioni per l'obiettivo "all" non riuscito
```
On archLinux

**Comment by javruben** [comment]
Would it be possible for you to install tmux using your package managed? For instance on ubunut: `sudo apt-get install tmux`. If tmux is installed it won't try to compile it and this error will go away.

**Comment by pietrondo** [comment]
tmux is already installed


Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by javruben** [comment]
Could you send the result of:
```
`which tmux`
```

**Comment by javruben** [comment]
And the result of `tmux -V`

**Comment by pietrondo** [comment]
/usr/bin/tmux

tmux -V
tmux 1.9a



Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by javruben** [comment]
Fixed with https://github.com/c9/install/commit/b88dda92212c5ba483f7cdd5ad9a0434ba6b101b

**Comment by IcyTesseract** [comment]
Issue still exists with configuration reported by @pietrondo. Compiling a program with the `-lutil` option does not throw this error from what I just tested outside of the installer.

**Comment by pietrondo** [comment]
yep.. same problem


Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by pietrondo** [comment]
on my ubuntu server no problem.. only on my desktop (archlinux)

on ubuntu (14.04)
tmux -V
tmux 1.8



Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

On Wed, Feb 11, 2015 at 10:07 PM, Pietro Capriata <pietro.capriata@gmail.com

**Comment by javruben** [comment]
@IcyTesseract Could you issue a PR to this repo with your fix?

@pietrondo Are you saying that the install script is still not detecting your tmux and is still trying to compile it?

**Comment by pietrondo** [comment]
yep:

gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/f_trace.c -o
../obj_g/f_trace.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_arg.c -o
../obj_g/fld_arg.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_attr.c -o
../obj_g/fld_attr.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_current.c -o
../obj_g/fld_current.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_def.c -o
../obj_g/fld_def.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_dup.c -o
../obj_g/fld_dup.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_ftchoice.c -o
../obj_g/fld_ftchoice.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_ftlink.c -o
../obj_g/fld_ftlink.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_info.c -o
../obj_g/fld_info.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_just.c -o
../obj_g/fld_just.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_link.c -o
../obj_g/fld_link.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_max.c -o
../obj_g/fld_max.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_move.c -o
../obj_g/fld_move.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_newftyp.c -o
../obj_g/fld_newftyp.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_opts.c -o
../obj_g/fld_opts.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_pad.c -o
../obj_g/fld_pad.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_page.c -o
../obj_g/fld_page.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_stat.c -o
../obj_g/fld_stat.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_type.c -o
../obj_g/fld_type.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fld_user.c -o
../obj_g/fld_user.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_cursor.c -o
../obj_g/frm_cursor.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_data.c -o
../obj_g/frm_data.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_def.c -o
../obj_g/frm_def.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_driver.c -o
../obj_g/frm_driver.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_hook.c -o
../obj_g/frm_hook.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_opts.c -o
../obj_g/frm_opts.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_page.c -o
../obj_g/frm_page.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_post.c -o
../obj_g/frm_post.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_req_name.c -o
../obj_g/frm_req_name.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_scale.c -o
../obj_g/frm_scale.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_sub.c -o
../obj_g/frm_sub.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_user.c -o
../obj_g/frm_user.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/frm_win.c -o
../obj_g/frm_win.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_alnum.c -o
../obj_g/fty_alnum.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_alpha.c -o
../obj_g/fty_alpha.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_enum.c -o
../obj_g/fty_enum.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_generic.c -o
../obj_g/fty_generic.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_int.c -o
../obj_g/fty_int.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_ipv4.c -o
../obj_g/fty_ipv4.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_num.c -o
../obj_g/fty_num.o
gcc -I../ncurses -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200 -g -DTRACE -c ../form/fty_regex.c -o
../obj_g/fty_regex.o
ar -curv ../lib/libform_g.a ../obj_g/f_trace.o ../obj_g/fld_arg.o
../obj_g/fld_attr.o ../obj_g/fld_current.o ../obj_g/fld_def.o
../obj_g/fld_dup.o ../obj_g/fld_ftchoice.o ../obj_g/fld_ftlink.o
../obj_g/fld_info.o ../obj_g/fld_just.o ../obj_g/fld_link.o
../obj_g/fld_max.o ../obj_g/fld_move.o ../obj_g/fld_newftyp.o
../obj_g/fld_opts.o ../obj_g/fld_pad.o ../obj_g/fld_page.o
../obj_g/fld_stat.o ../obj_g/fld_type.o ../obj_g/fld_user.o
../obj_g/frm_cursor.o ../obj_g/frm_data.o ../obj_g/frm_def.o
../obj_g/frm_driver.o ../obj_g/frm_hook.o ../obj_g/frm_opts.o
../obj_g/frm_page.o ../obj_g/frm_post.o ../obj_g/frm_req_name.o
../obj_g/frm_scale.o ../obj_g/frm_sub.o ../obj_g/frm_user.o
../obj_g/frm_win.o ../obj_g/fty_alnum.o ../obj_g/fty_alpha.o
../obj_g/fty_enum.o ../obj_g/fty_generic.o ../obj_g/fty_int.o
../obj_g/fty_ipv4.o ../obj_g/fty_num.o ../obj_g/fty_regex.o
r - ../obj_g/f_trace.o
r - ../obj_g/fld_arg.o
r - ../obj_g/fld_attr.o
r - ../obj_g/fld_current.o
r - ../obj_g/fld_def.o
r - ../obj_g/fld_dup.o
r - ../obj_g/fld_ftchoice.o
r - ../obj_g/fld_ftlink.o
r - ../obj_g/fld_info.o
r - ../obj_g/fld_just.o
r - ../obj_g/fld_link.o
r - ../obj_g/fld_max.o
r - ../obj_g/fld_move.o
r - ../obj_g/fld_newftyp.o
r - ../obj_g/fld_opts.o
r - ../obj_g/fld_pad.o
r - ../obj_g/fld_page.o
r - ../obj_g/fld_stat.o
r - ../obj_g/fld_type.o
r - ../obj_g/fld_user.o
r - ../obj_g/frm_cursor.o
r - ../obj_g/frm_data.o
r - ../obj_g/frm_def.o
r - ../obj_g/frm_driver.o
r - ../obj_g/frm_hook.o
r - ../obj_g/frm_opts.o
r - ../obj_g/frm_page.o
r - ../obj_g/frm_post.o
r - ../obj_g/frm_req_name.o
r - ../obj_g/frm_scale.o
r - ../obj_g/frm_sub.o
r - ../obj_g/frm_user.o
r - ../obj_g/frm_win.o
r - ../obj_g/fty_alnum.o
r - ../obj_g/fty_alpha.o
r - ../obj_g/fty_enum.o
r - ../obj_g/fty_generic.o
r - ../obj_g/fty_int.o
r - ../obj_g/fty_ipv4.o
r - ../obj_g/fty_num.o
r - ../obj_g/fty_regex.o
ranlib ../lib/libform_g.a
make[1]: uscita dalla directory "/home/pietro/.c9/ncurses-5.9/form"
cd test && make DESTDIR="" all
make[1]: ingresso nella directory "/home/pietro/.c9/ncurses-5.9/test"
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/background.c -o
../objects/background.o
gcc -O2 --param max-inline-insns-single=1200  -o background
../objects/background.o  -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE
-DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2
--param max-inline-insns-single=1200  `echo "-static -L../lib -lform -lmenu
-lpanel -lncurses  -dynamic  -ldl " | sed -e 's/-lform.*-lpanel[^ ]*//'`
-lutil  -lm
/usr/bin/ld: impossibile trovare -lutil



Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by javruben** [comment]
Could you contact me on skype to debug this interactively? My skype name is "javruben".

**Comment by pietrondo** [comment]
ok... could we chat? At the moment my microphone doesn't work.. thx

On Wed, Feb 11, 2015 at 10:54 PM, Ruben Daniels <notifications@github.com>
wrote:

> javruben





Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by javruben** [comment]
Chat is fine, I just want to see your screen and be interactive with you. I am assuming you are on a local machine. If you are in the cloud, well then it would be easier :)

**Comment by pietrondo** [comment]
yep
Is my local machine.
I have added you on skype



Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by IcyTesseract** [comment]
@javruben Sorry I haven't got a fix. If it helps this is a ncurses specific issue. Compiling ncurses outside of the install script fails with the same error.

**Comment by javruben** [comment]
@pietrondo Not seeing the request. What is your username?

**Comment by pietrondo** [comment]
I have removed "-lutil" from about ncurses/test  Makefile

and now




../lib/libncurses.a(lib_mouse.o): nella funzione "load_gpm_library":
lib_mouse.c:(.text+0x4cb): attenzione: Using 'dlopen' in statically linked
applications requires at runtime the shared libraries from the glibc
version used for linking
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/demo_keyok.c -o
../objects/demo_keyok.o
gcc -O2 --param max-inline-insns-single=1200  -o demo_keyok
../objects/demo_keyok.o  -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE
-DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2
--param max-inline-insns-single=1200  `echo "-static -L../lib -lform -lmenu
-lpanel -lncurses  -dynamic  -ldl " | sed -e 's/-lform.*-lpanel[^ ]*//'`
-lm
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/demo_menus.c -o
../objects/demo_menus.o
gcc -O2 --param max-inline-insns-single=1200  -o demo_menus
../objects/demo_menus.o  -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE
-DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2
--param max-inline-insns-single=1200  -static -L../lib -lform -lmenu
-lpanel -lncurses  -dynamic  -ldl   -lm
../lib/libncurses.a(lib_mouse.o): nella funzione "load_gpm_library":
lib_mouse.c:(.text+0x4cb): attenzione: Using 'dlopen' in statically linked
applications requires at runtime the shared libraries from the glibc
version used for linking
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/demo_panels.c -o
../objects/demo_panels.o
gcc -O2 --param max-inline-insns-single=1200  -o demo_panels
../objects/demo_panels.o  -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE
-DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2
--param max-inline-insns-single=1200  -static -L../lib -lform -lmenu
-lpanel -lncurses  -dynamic  -ldl   -lm
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/demo_termcap.c -o
../objects/demo_termcap.o
gcc -O2 --param max-inline-insns-single=1200  -o demo_termcap
../objects/demo_termcap.o  -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE
-DNDEBUG -I. -I../include -I/home/pietro/.c9/local/include/ncurses -O2
--param max-inline-insns-single=1200  -static -L../lib -lncurses -dynamic
-ldl   -lm
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/demo_terminfo.c -o
../objects/demo_terminfo.o
gcc -O2 --param max-inline-insns-single=1200  -o demo_terminfo
../objects/demo_terminfo.o  -I. -I. -I../test -DHAVE_CONFIG_H
-D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -static -L../lib -lncurses -dynamic -ldl   -lm
gcc -I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I.
-I../include -I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  -c ../test/ditto.c -o ../objects/ditto.o
gcc -O2 --param max-inline-insns-single=1200  -o ditto ../objects/ditto.o
-I. -I. -I../test -DHAVE_CONFIG_H  -D_GNU_SOURCE -DNDEBUG -I. -I../include
-I/home/pietro/.c9/local/include/ncurses -O2 --param
max-inline-insns-single=1200  `echo "-static -L../lib -lform -lmenu -lpanel
-lncurses  -dynamic  -ldl " | sed -e 's/-lform.*-lpanel[^ ]*//'`  -lm
../objects/ditto.o: nella funzione "open_tty":
ditto.c:(.text+0x284): riferimento non definito a "openpty"
collect2: error: ld returned 1 exit status
Makefile:274: set di istruzioni per l'obiettivo "ditto" non riuscito
make: *** [ditto] Errore 1



Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by alessioguglielmo** [comment]
I have some problem with 
'''
node server.js
'''
it returns nothing
My system is Ubuntu 14.10

**Comment by javruben** [comment]
@alessioguglielmo this seems unrelated to this issue, or to the installer. Could you add an issue here: github.com/c9/core/issues and please add *much* more information in order to for us to help you debug your problem.

**Comment by javruben** [comment]
@pietrondo You left the hangout. I dont think you ever saw my chat messages.

You might want to check out the solutions in this issue: https://github.com/c9/install/issues/23

**Comment by alessioguglielmo** [comment]
@javruben 

I followed the 3-steps installation and installed nodejs. Not much to say really... the system silently fail the running
However I posted it in issues section on c9 core in github.

**Comment by BadOPCode** [comment]
Hey I pinned down what exactly is failing.  It's just the tests in ncurses.  If you configure ncurses with --without-tests --without-cxx  the build is successful.

**Comment by javruben** [comment]
Thanks @BadOPCode!
